{'activation': 'softplus', 'batch_size': 4, 'd_k': 128, 'd_model': 128, 'd_rnn': 64, 'data': 'data/Breakfast/', 'device': 'cuda', 'dropout': 0.1, 'epochs': 50, 'learning_rate': 0.001, 'n_head': 4, 'n_layers': 4, 'smooth': 0.1}
Loading All Datasets...
45 9
[ Epoch 1 ]


  - (Validation) :   0%|                                                                                                                                                                                               | 0/32 [00:00<?, ?it/s]
  - (Training)    loglikelihood:  0.22746, accuracy:  0.18044, RMSE:  0.87525, elapse: 0.126 min
  - (Testing)     loglikelihood:  0.52065, accuracy:  0.22909, RMSE:  1.08875, elapse: 0.059 min
  - [Info] Maximum ll:  0.52065, Maximum accuracy:  0.22909, Minimum RMSE:  1.08875
improvement in epoch 1


  - (Validation) :   0%|                                                                                                                                                                                               | 0/32 [00:00<?, ?it/s]
  - (Training)    loglikelihood:  0.64129, accuracy:  0.23320, RMSE:  0.89050, elapse: 0.111 min
  - (Testing)     loglikelihood:  0.69183, accuracy:  0.24067, RMSE:  1.07732, elapse: 0.058 min
  - [Info] Maximum ll:  0.69183, Maximum accuracy:  0.24067, Minimum RMSE:  1.07732
improvement in epoch 2



  - (Training)   :  55%|████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                                                | 67/121 [00:05<00:03, 16.15it/s]


  - (Training)   :   0%|                                                                                                                                                                                              | 0/121 [00:00<?, ?it/s]
  - (Testing)     loglikelihood:  0.75648, accuracy:  0.26770, RMSE:  1.07263, elapse: 0.062 min
  - [Info] Maximum ll:  0.75648, Maximum accuracy:  0.26770, Minimum RMSE:  1.07263
improvement in epoch 3


  - (Training)   :  56%|█████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                                               | 68/121 [00:05<00:03, 15.98it/s]


  - (Validation) :   3%|█████▋                                                                                                                                                                                 | 1/32 [00:02<01:32,  2.99s/it]
  - (Testing)     loglikelihood:  0.79205, accuracy:  0.18018, RMSE:  1.07321, elapse: 0.058 min
  - [Info] Maximum ll:  0.79205, Maximum accuracy:  0.26770, Minimum RMSE:  1.07263



  - (Training)   :  56%|█████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                                               | 68/121 [00:05<00:03, 16.33it/s]

  - (Validation) :   0%|                                                                                                                                                                                               | 0/32 [00:00<?, ?it/s]
  - (Testing)     loglikelihood:  0.85913, accuracy:  0.20077, RMSE:  1.07252, elapse: 0.061 min
  - [Info] Maximum ll:  0.85913, Maximum accuracy:  0.26770, Minimum RMSE:  1.07252



Traceback (most recent call last):
  File "C:\Users\mich0003\AppData\Local\anaconda3\envs\proactive\lib\site-packages\torch\utils\data\dataloader.py", line 779, in _try_get_data
    data = self._data_queue.get(timeout=timeout)
  File "C:\Users\mich0003\AppData\Local\anaconda3\envs\proactive\lib\multiprocessing\queues.py", line 105, in get
    raise Empty
_queue.Empty
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "C:\Users\mich0003\Repos\BachelorPP\proactive\strategies\architecture\hawkes_training_wandb.py", line 65, in train
    train_event, train_type, train_time = train_epoch(model, trainloader, optimizer, pred_loss_func, pred_loss_goal, config, epoch)
  File "C:\Users\mich0003\Repos\BachelorPP\proactive\strategies\architecture\hawkes_training_wandb.py", line 109, in train_epoch
    desc='  - (Training)   ', leave=False):
  File "C:\Users\mich0003\AppData\Local\anaconda3\envs\proactive\lib\site-packages\tqdm\std.py", line 1178, in __iter__
    for obj in iterable:
  File "C:\Users\mich0003\AppData\Local\anaconda3\envs\proactive\lib\site-packages\torch\utils\data\dataloader.py", line 363, in __next__
    data = self._next_data()
  File "C:\Users\mich0003\AppData\Local\anaconda3\envs\proactive\lib\site-packages\torch\utils\data\dataloader.py", line 974, in _next_data
    idx, data = self._get_data()
  File "C:\Users\mich0003\AppData\Local\anaconda3\envs\proactive\lib\site-packages\torch\utils\data\dataloader.py", line 941, in _get_data
    success, data = self._try_get_data()
  File "C:\Users\mich0003\AppData\Local\anaconda3\envs\proactive\lib\site-packages\torch\utils\data\dataloader.py", line 792, in _try_get_data
    raise RuntimeError('DataLoader worker (pid(s) {}) exited unexpectedly'.format(pids_str))
RuntimeError: DataLoader worker (pid(s) 18076, 20664) exited unexpectedly